import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

import { Toaster } from "@/components/ui/sonner";
import Navbar from "@/components/web/navbar/Navbar";


const montserratHeading = Montserrat({subsets:['latin'],variable:'--font-heading'});

const inter = Inter({subsets:['latin'],variable:'--font-sans'});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", inter.variable, montserratHeading.variable)}
    >
      <body className="min-h-full flex flex-col">
        <Navbar/>
        <main className="md:mx-10 lg:mx-20 mx-5 my-10 flex-1">
     {children}
        </main>
        <Toaster/>
   
        </body>
    </html>
  );
}
