import type { Metadata } from "next";
import { Geist, Geist_Mono, JetBrains_Mono, Inter, Figtree } from "next/font/google";
import "./globals.css";
import NavBar from "../components/web/Navbar";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "../components/theme-provider";

const figtree = Figtree({subsets:['latin'],variable:'--font-sans'});

const jetbrainsMono = JetBrains_Mono({ subsets: ['latin'], variable: '--font-mono' });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en" className={cn(jetbrainsMono.variable, "font-sans", figtree.variable)}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange>
             <main className="mt-10 max-w-7xl mx-auto w-full px-4 md:px-6 lg:px-8">
          <NavBar />
          {children}
        </main>

        </ThemeProvider>
       

      </body>
    </html>
  );
}
